repos:
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-use-type-annotations

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests==2.26.3]

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a4
    hooks:
    - id: pylint
      name: "pylint main"
      exclude: "tests/"
      args: [
        --max-line-length=120,
        --disable=invalid-name,
        --disable=missing-docstring,
        --disable=import-error,
      ]
    - id: pylint
      name: "pylint tests"
      exclude: "scripts/"
      args: [
          --max-line-length=120,
          --disable=missing-docstring,
          --disable=invalid-name,
          --disable=import-error,
          --disable=too-many-arguments,
          --disable=unused-argument,
      ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: end-of-file-fixer

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args: [--max-line-length=120]

-   repo: local
    hooks:
      - id: check-circleci-config
        name: check CircleCI config
        entry: circleci --skip-update-check config validate
        language: system
        files: ^.circleci/config.yml
